### ISSUE TITLE
Serilog page has invalid HOCON string

### ISSUE THREAD

**Issue by screamish** [akkadotnet/akkadotnet.github.com#14]
I'm new to Akka.Net so please forgive any inaccuracies here.

The docs at http://getakka.net/docs/Serilog have the following HOCON string

```
var system = ActorSystem.Create("my-test-system", "akka { logLevel=INFO,  loggers=['Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog']}");
```

The single quotes seem to cause the parse to fail. Changing them to escaped double quotes fixed my logging.

**Comment by Danthar** [comment]
Thank you for your remarks. This problem has since then been resolved
