### ISSUE TITLE
/docs/CircuitBreaker 'Examples' section is invalid

### ISSUE THREAD

**Issue by CreepyGnome** [akkadotnet/akkadotnet.github.com#17]
The CircuitBreaker docs page has a section for examples but they do not display. Instead it has ".. includecode::" statements, all of which look like they are trying to include files that are wrong and apparently there is no directories on your website github repo matching those listed in the includecode statement.

The F# and C# Initialization sections are trying to include the wrong file, so if they did exist they would show incorrect examples for the section they are attempted to be included in.

The F# call protection is referencing a scala file instead of an fs file. So if it existed they would still be incorrect.

The C# call protection is referencing a java file instead of a cs. file. So if it existed they would still be incorrect.

**Comment by Danthar** [comment]
Thank you for your remarks. The CircuitBreaker page has since then been overhauled
